// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCywN9wXh1Fyq5jo6GphXGkWKmOMUgsOmI',
    appId: '1:500832260835:web:208b3329f716066b5eabd6',
    messagingSenderId: '500832260835',
    projectId: 'authtutorial-8b368',
    authDomain: 'authtutorial-8b368.firebaseapp.com',
    storageBucket: 'authtutorial-8b368.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-l7AsdjwvtzxqHfC4KhIT5uvF2ZFqU3A',
    appId: '1:500832260835:android:53a025eed1a9dab85eabd6',
    messagingSenderId: '500832260835',
    projectId: 'authtutorial-8b368',
    storageBucket: 'authtutorial-8b368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1MUH7WnvTd0bxnY3b3TrBtlJXRSgamm8',
    appId: '1:500832260835:ios:15908c72c13459755eabd6',
    messagingSenderId: '500832260835',
    projectId: 'authtutorial-8b368',
    storageBucket: 'authtutorial-8b368.appspot.com',
    iosBundleId: 'com.example.loginp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1MUH7WnvTd0bxnY3b3TrBtlJXRSgamm8',
    appId: '1:500832260835:ios:52b62ebd310db9d25eabd6',
    messagingSenderId: '500832260835',
    projectId: 'authtutorial-8b368',
    storageBucket: 'authtutorial-8b368.appspot.com',
    iosBundleId: 'com.example.loginp.RunnerTests',
  );
}
