// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR9_M4Uln5kdidr-p72QsN2nwhXAJdx2o',
    appId: '1:481211800646:web:6bcd9db048a91f215dbe47',
    messagingSenderId: '481211800646',
    projectId: 'sneakstoreclg',
    authDomain: 'sneakstoreclg.firebaseapp.com',
    storageBucket: 'sneakstoreclg.appspot.com',
    measurementId: 'G-69NSV2BBRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwD-_mJIS1gW3eYhcHoI-oGwiT-IOkuXE',
    appId: '1:481211800646:android:33ba512a5c2efb1c5dbe47',
    messagingSenderId: '481211800646',
    projectId: 'sneakstoreclg',
    storageBucket: 'sneakstoreclg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6AJjqXro_Rxc1-fRQH-cYS93eNGTjMp0',
    appId: '1:481211800646:ios:9f9f0d36277bd5265dbe47',
    messagingSenderId: '481211800646',
    projectId: 'sneakstoreclg',
    storageBucket: 'sneakstoreclg.appspot.com',
    iosBundleId: 'com.example.sneakstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6AJjqXro_Rxc1-fRQH-cYS93eNGTjMp0',
    appId: '1:481211800646:ios:566e5498337d31755dbe47',
    messagingSenderId: '481211800646',
    projectId: 'sneakstoreclg',
    storageBucket: 'sneakstoreclg.appspot.com',
    iosBundleId: 'com.example.sneakstore.RunnerTests',
  );
}
